name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write   #allow workflow to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Install doxygen (and graphviz for diagrams)
      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # 3. Generate docs
      - name: Build Doxygen
        run: doxygen Doxyfile

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html

